### ISSUE TITLE
Help backporting to 1.10.2

### ISSUE THREAD

**Issue by Tri0de** [iChun/GeneralLaymansAestheticSpyingScreen#10]
I'll be honest Ive made a big fat mess of your code in the process, but I have a working port of GLASS working in 1.10.2

The main issue is that currently the access transformers conflict with IChunUtil, and so the mod works perfectly in dev, but not at all in compiled.

The rep is still private but I've added you, think you can help with this access transformer issue?

https://github.com/Best108/1.10-Glass-Mod/invitations

**Comment by iChun** [comment]
Wait, why was it so hard to backport the mod? Mostly you had to do was rip out the world portal module for 1.12.2 and put it in place in iChunUtil 1.10.2, and backport GLASS's code to 1.10.2 (which wouldn't have been much work).

**Comment by Best108** [comment]
O>O

**Comment by Tri0de** [comment]
I ended settling on a compromise, throwing the glass code into IChunUtil 1.10 directly. Not pretty but it works, thanks for the suggestions mate.

**Comment by Tri0de** [comment]
Hey IChun since you're using the GNU license, would it be ok if I posted the 1.10 port onto CurseForge?

**Comment by steampunko** [comment]
I don't think iChun is checking the github issues out right now
