### ISSUE TITLE
Cross dimension feature?

### ISSUE THREAD

**Issue by theoparis** [iChun/GeneralLaymansAestheticSpyingScreen#23]
Is there a way to use the GLASS terminal and projector across dimensions? The channel showed up but then disappeared after I tried to activate the projector.
If not, an you please add this feature?
Thanks.

**Comment by theoparis** [comment]
I was thinking I could use this along with chicken chunks' chunk loader to keep the terminal rendering, but that does not seem to work.

**Comment by iChun** [comment]
Uh oh, the channel showing up is a bug, actually. GLASS/World Portals do
not work cross dimension or long distances. I'm yet to try and get them to
work as such.

**Comment by theoparis** [comment]
Ok 👍 
Let me know when you get this implemented! Thanks.
