### ISSUE TITLE
Mod does not add anything despite being installed correctly

### ISSUE THREAD

**Issue by oChitWalltap** [iChun/GeneralLaymansAestheticSpyingScreen#27]
![2019-07-16_00 54 08](https://user-images.githubusercontent.com/52953341/61276394-ce3a3480-a764-11e9-9f90-7815aa92040e.png)
![2019-07-16_00 54 42](https://user-images.githubusercontent.com/52953341/61276395-ced2cb00-a764-11e9-863f-624521b6850c.png)

I'm using Forge 14.23.5.2838 and iChunUtil 7.2.1. As stated in the title and as shown in the pictures, the mod doesn't add anything despite being installed correctly. Judging by the fact that there are recently posted issues though, it would seem that there are people who currently have it working. So, to those people, what am I doing wrong? Is there a special version of Forge or iChunUtil that I should be using, or is it something else?

**Comment by Rannulfus** [comment]
It's doesn't get it's own tab, instead it's all in the redstone tab.

**Comment by oChitWalltap** [comment]
> It's doesn't get it's own tab, instead it's all in the redstone tab.

Oh, I see. Probably could have just looked there, eh?
