### ISSUE TITLE
GLASS not working properly

### ISSUE THREAD

**Issue by MightDarkGames** [iChun/GeneralLaymansAestheticSpyingScreen#29]
When I'm going to make the "simulation", it makes appear a white sky, everything, even if the Channel is in the water looking down, I need some help solving this. I have some mods that could be the problem or my graphic settings to make my FPS better (I watched a video...). Here's the link of teh video and my mods including the GLASS mod:

https://www.youtube.com/watch?v=AtVrcNIIN6I

[1.12.2.zip](https://github.com/iChun/GeneralLaymansAestheticSpyingScreen/files/3880009/1.12.2.zip)

**Comment by AdamRamos562** [comment]
Remove optifine

**Comment by MightDarkGames** [comment]
Thanks!
It worked, costing my FPS, but it worked...
Closed.
