### ISSUE TITLE
I get a crash on launch when trying to launch the game with only this mod and ichunutils

### ISSUE THREAD

**Issue by 3nd0fw0r1d** [iChun/GeneralLaymansAestheticSpyingScreen#3]
Crash log is in pastebin, I'm using the latest forge release as well as latest curseforge-available GLASS and ichunutils jars

https://pastebin.com/Brv2L6Mw

**Comment by iChun** [comment]
GLASS doesn't work on 1.12 because it's missing an event added to Forge
later on. That's why it's not marked for 1.12 on CF

**Comment by 3nd0fw0r1d** [comment]
...Derp

**Comment by AtomicToast84** [comment]
Then what version does it work on ;-;
