### ISSUE TITLE
its not 1.7.10 

### ISSUE THREAD

**Issue by BallisticOK** [iChun/GeneralLaymansAestheticSpyingScreen#35]
this would be soo cool to add to my modpack im making for my friends byt my mod pack in 1.7.10 and this is 1.12.2

**Comment by iChun** [comment]
https://howoldisminecraft1710.today/

It would be cool, yes, but not practical for me to still be supporting mods on such an old version of Minecraft. 

Both the world portal tech that this mod uses and this mod itself are open source, if you'd like you can attempt to back port the mods to 1.7.10 for your own purpose, but I won't be the one doing it, sorry.
