### ISSUE TITLE
Rendering only 1 block?

### ISSUE THREAD

**Issue by marcikoHub** [iChun/GeneralLaymansAestheticSpyingScreen#53]
My mc can only render 1 block infront of Renderer. Also renderer is black. 

- [ ] Problem on my side?
Btw. I was using OptiFine + G.L.A.S.S.

**Comment by iChun** [comment]
GLASS is not compatible with Optifine. There are no plans to address this at this point in time as I no longer support any of my mods for 1.12.2 and older.
